kind: Namespace
apiVersion: v1
metadata:
  name: llm-rag
  labels:
    opendatahub.io/dashboard: 'true'
    - manager: pod-security-admission-label-synchronization-controller
      operation: Apply
      apiVersion: v1
      time: '2025-09-04T13:10:45Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            'f:pod-security.kubernetes.io/audit': {}
            'f:pod-security.kubernetes.io/audit-version': {}
            'f:pod-security.kubernetes.io/warn': {}
            'f:pod-security.kubernetes.io/warn-version': {}
    - manager: cluster-policy-controller
      operation: Update
      apiVersion: v1
      time: '2025-09-04T13:10:44Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:openshift.io/sa.scc.mcs': {}
            'f:openshift.io/sa.scc.supplemental-groups': {}
            'f:openshift.io/sa.scc.uid-range': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: v1
      time: '2025-09-04T13:10:44Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/description': {}
            'f:openshift.io/display-name': {}
            'f:openshift.io/requester': {}
          'f:labels':
            .: {}
            'f:kubernetes.io/metadata.name': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: v1
      time: '2025-09-04T13:10:44Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:finalizers': {}
      subresource: finalize
    - manager: unknown
      operation: Update
      apiVersion: v1
      time: '2025-09-04T13:10:44Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            'f:opendatahub.io/dashboard': {}
    - manager: openshift-pipelines-operator
      operation: Update
      apiVersion: v1
      time: '2025-09-04T13:10:46Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            'f:openshift-pipelines.tekton.dev/namespace-reconcile-version': {}
spec:
  finalizers:
    - kubernetes